apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conductor-data-pvc
  namespace: default
  labels:
    app: conductor-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
